'use client'
import { useRouter } from 'next/navigation'

export default function Terms() {
  const router = useRouter()
  const star = '\u2726'

  return (
    <main style={{background:'#0D0B1E ',minHeight:'100vh',color:'#E8E0FF',fontFamily:'Georgia,serif'}}>
      <div style={{maxWidth:'680px',margin:'0 auto',padding:'0 18px 60px'}}>

        <nav style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'22px 0'}}>
          <div style={{display:'flex',alignItems:'center',gap:'10px'}}>
            <img src="/logo.png" alt="CelestiaSOUL" style={{width:'56px',height:'56px',borderRadius:'50%',objectFit:'cover',boxShadow:'0 0 16px rgba(200,168,255,0.5)',border:'1px solid rgba(200,168,255,0.25)'}}/>
            <span style={{fontStyle:'italic',fontSize:'20px',letterSpacing:'3px',background:'linear-gradient(135deg,#DDD0FF,#FFE8C8,#C8E8FF)',WebkitBackgroundClip:'text',WebkitTextFillColor:'transparent'}}>CelestiaSOUL</span>
          </div>
          <button onClick={()=>router.push('/')} style={{fontStyle:'italic',fontSize:'13px',letterSpacing:'3px',color:'rgba(200,168,255,0.5)',cursor:'pointer',border:'1px solid rgba(200,168,255,0.2)',borderRadius:'20px',padding:'6px 16px',background:'transparent'}}>Home</button>
        </nav>

        <div style={{textAlign:'center',marginBottom:'40px'}}>
          <p style={{fontFamily:'sans-serif',fontSize:'10px',letterSpacing:'8px',color:'rgba(200,168,255,0.4)',marginBottom:'8px'}}>{star} LEGAL {star}</p>
          <h1 style={{fontStyle:'italic',fontWeight:300,fontSize:'40px',letterSpacing:'4px',background:'linear-gradient(135deg,#DDD0FF,#FFE8C8,#C8E8FF)',WebkitBackgroundClip:'text',WebkitTextFillColor:'transparent',margin:'0 0 12px'}}>Terms of Service</h1>
          <p style={{fontFamily:'sans-serif',fontSize:'12px',color:'rgba(200,168,255,0.4)',letterSpacing:'2px'}}>Last updated: April 7, 2026</p>
        </div>

        {[
          {title:'1. Acceptance of Terms',content:`By accessing or using CelestiaSOUL, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our service. CelestiaSOUL reserves the right to update these terms at any time, and continued use of the service constitutes acceptance of any changes.`},
          {title:'2. Description of Service',content:`CelestiaSOUL is a spiritual wellness subscription platform that provides Sacred astrology readings, guided breathwork sessions, healing Solfeggio frequencies, meditation music, moon phase rituals, and a sacred journal. Our services are intended for personal spiritual wellness and entertainment purposes only.`},
          {title:'3. Disclaimer — Not Medical Advice',content:`CelestiaSOUL is a spiritual wellness app for entertainment and personal growth purposes only. Our astrology readings, breathwork guidance, and healing frequencies are NOT a substitute for professional medical, psychological, or therapeutic advice. Always consult a qualified healthcare professional for medical concerns.`},
          {title:'4. Subscription & Payment',content:`CelestiaSOUL offers a 3-day free trial followed by a $10 per month subscription. Your subscription will automatically renew each month unless cancelled. You may cancel your subscription at any time before the renewal date. Refunds are not provided for partial months. All payments are processed securely through Stripe.`},
          {title:'5. Free Trial',content:`New users receive a 3-day free trial upon subscribing. No charge will be made during the trial period. After the trial ends, your subscription will automatically begin at $10 per month. You may cancel before the trial ends to avoid any charges.`},
          {title:'6. User Account',content:`You are responsible for maintaining the confidentiality of your account credentials. You agree to provide accurate information when creating your account. You must be at least 13 years of age to use CelestiaSOUL. One account per person is permitted.`},
          {title:'7. Astrological Content',content:`All astrology readings, moon phase guidance, and cosmic recommendations provided by CelestiaSOUL are generated by artificial intelligence and are intended for entertainment and personal reflection purposes only. We make no claims about the accuracy, completeness, or reliability of astrological information.`},
          {title:'8. Intellectual Property',content:`All content on CelestiaSOUL including but not limited to text, graphics, logos, audio files, and software is the property of CelestiaSOUL and is protected by applicable intellectual property laws. You may not reproduce, distribute, or create derivative works without our express written permission.`},
          {title:'9. Prohibited Uses',content:`You agree not to use CelestiaSOUL for any unlawful purpose, to attempt to gain unauthorized access to our systems, to reverse engineer or copy our software, to harass or harm other users, or to use our service in any way that could damage or impair its functionality.`},
          {title:'10. Limitation of Liability',content:`CelestiaSOUL shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of our service. Our total liability to you for any claims shall not exceed the amount you paid for the service in the 3 months preceding the claim.`},
          {title:'11. Governing Law',content:`These Terms of Service are governed by the laws of the State of Arizona, United States. Any disputes arising from these terms shall be resolved in the courts of Maricopa County, Arizona.`},
          {title:'12. Contact Us',content:`If you have any questions about these Terms of Service, please contact us at support@celestiasoul.com. We will respond to all inquiries within 48 hours.`},
        ].map(({title,content})=>(
          <div key={title} style={{marginBottom:'28px',paddingBottom:'28px',borderBottom:'1px solid rgba(200,168,255,0.08)'}}>
            <h2 style={{fontStyle:'italic',fontSize:'18px',letterSpacing:'2px',color:'#C8A8FF',marginBottom:'12px',fontWeight:300}}>{title}</h2>
            <p style={{fontFamily:'sans-serif',fontSize:'13px',color:'rgba(220,210,255,0.65)',lineHeight:1.9,margin:0}}>{content}</p>
          </div>
        ))}

        <div style={{background:'rgba(255,255,255,0.02)',border:'1px solid rgba(200,168,255,0.08)',borderRadius:'16px',padding:'22px',textAlign:'center',marginTop:'20px'}}>
          <p style={{fontStyle:'italic',fontSize:'13px',color:'rgba(200,168,255,0.5)',marginBottom:'16px'}}>Questions about our terms?</p>
          <p style={{fontFamily:'sans-serif',fontSize:'12px',color:'rgba(200,168,255,0.4)',letterSpacing:'1px',marginBottom:'16px'}}>support@celestiasoul.com</p>
          <div style={{display:'flex',gap:'12px',justifyContent:'center',flexWrap:'wrap'}}>
            <button onClick={()=>router.push('/privacy')} style={{padding:'8px 20px',background:'transparent',border:'1px solid rgba(200,168,255,0.2)',borderRadius:'20px',fontStyle:'italic',fontSize:'12px',letterSpacing:'2px',color:'rgba(200,168,255,0.5)',cursor:'pointer'}}>Privacy Policy</button>
            <button onClick={()=>router.push('/')} style={{padding:'8px 20px',background:'rgba(138,90,255,0.2)',border:'1px solid rgba(200,168,255,0.3)',borderRadius:'20px',fontStyle:'italic',fontSize:'12px',letterSpacing:'2px',color:'#C8A8FF',cursor:'pointer'}}>Back to CelestiaSOUL</button>
          </div>
        </div>

      </div>
    </main>
  )
}
